syntax = "proto3";

package com.android.launcherconnector;

import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/delete/delete_result_request.proto";
import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/delete/delete_result_response.proto";
import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/event/notify_event_request.proto";
import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/event/notify_event_response.proto";
import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/report/report_result_request.proto";
import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/report/report_result_response.proto";
import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/search/get_search_results_request.proto";
import "packages/apps/Launcher3/LauncherConnector/src/com/android/launcherconnector/proto/search/get_search_results_response.proto";

option java_multiple_files = true;
option java_package = "com.android.launcherconnector.proto";
option java_outer_classname = "LauncherConnectorProto";

// The LauncherConnector service definition.
service LauncherConnector {
  // Returns search results for a given query.
  rpc GetSearchResults(stream com.android.launcherconnector.proto.GetSearchResultsRequest)
      returns (stream com.android.launcherconnector.proto.GetSearchResultsResponse);

  // Deletes a result.
  rpc DeleteResult(com.android.launcherconnector.proto.DeleteResultRequest) returns (com.android.launcherconnector.proto.DeleteResultResponse);

  // Reports a result.
  rpc ReportResult(com.android.launcherconnector.proto.ReportResultRequest) returns (com.android.launcherconnector.proto.ReportResultResponse);

  // Notifies of an event.
  rpc NotifyEvent(com.android.launcherconnector.proto.NotifyEventRequest) returns (com.android.launcherconnector.proto.NotifyEventResponse);
}
